name: example
description: A example tus client Flutter project.

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  another_tus_client:
    path: ../
  cross_file: ^0.3.4
  file_picker: ^9.0.2
  url_launcher: ^6.3.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.1
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
